version: "3"

services:
  nuxt:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_NUXT"
    restart: always
    ports:
      - "4114:4114"
    command:
      "npm run start"
    networks:
      - admin-network



  nginx:
    image: nginx:1.13
    container_name: "${COMPOSE_PROJECT_NAME}_NGINX"
    ports:
      - "4119:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - nuxt
    networks:
      - admin-network
#Docker Networks
networks:
  admin-network:
    driver: bridge
